INSERT INTO diagnoses (name) VALUES
                                 ('Hypertension'),
                                 ('Diabetes Mellitus'),
                                 ('Coronary Artery Disease'),
                                 ('Hyperlipidemia'),
                                 ('Chronic Liver Disease'),
                                 ('Gastritis'),
                                 ('Asthma'),
                                 ('Halitosis'),
                                 ('Depression'),
                                 ('Vitamin D Deficiency'),
                                 ('Psoriasis'),
                                 ('Eczema'),
                                 ('Diarrhea'),
                                 ('Urinary Tract Infection'),
                                 ('Anemia'),
                                 ('Migraine'),
                                 ('Tuberculosis'),
                                 ('Pneumonia'),
                                 ('Bronchitis'),
                                 ('Hepatitis B'),
                                 ('Hepatitis C'),
                                 ('Sinusitis'),
                                 ('Allergic Rhinitis'),
                                 ('Otitis Media'),
                                 ('Glaucoma'),
                                 ('Cataract'),
                                 ('Conjunctivitis'),
                                 ('Acne Vulgaris'),
                                 ('Peptic Ulcer Disease'),
                                 ('GERD (Gastroesophageal Reflux Disease)'),
                                 ('Obesity'),
                                 ('Thyroid Disorder'),
                                 ('Insomnia'),
                                 ('Anxiety Disorder'),
                                 ('Gout'),
                                 ('Osteoarthritis'),
                                 ('Rheumatoid Arthritis'),
                                 ('Back Pain'),
                                 ('Sciatica'),
                                 ('Epilepsy'),
                                 ('Stroke'),
                                 ('Chickenpox'),
                                 ('Measles'),
                                 ('Dengue Fever'),
                                 ('Malaria'),
                                 ('COVID-19'),
                                 ('Influenza'),
                                 ('Appendicitis'),
                                 ('Gallstones'),
                                 ('Kidney Stones'),
                                 ('COPD (Chronic Obstructive Pulmonary Disease)'),
                                 ('Pancreatitis'),
                                 ('Liver Cirrhosis'),
                                 ('HIV/AIDS'),
                                 ('Tonsillitis'),
                                 ('Pharyngitis'),
                                 ('Otitis Externa'),
                                 ('Meningitis'),
                                 ('Parkinson\'s Disease'),
                                 ('Alzheimer\'s Disease'),
                                 ('Leukemia'),
                                 ('Lymphoma'),
                                 ('Breast Cancer'),
                                 ('Lung Cancer'),
                                 ('Colon Cancer'),
                                 ('Prostate Cancer'),
                                 ('Skin Cancer'),
                                 ('Melanoma'),
                                 ('Multiple Sclerosis'),
                                 ('Systemic Lupus Erythematosus'),
                                 ('Polycystic Ovary Syndrome'),
                                 ('Endometriosis'),
                                 ('Menstrual Disorder'),
                                 ('Infertility'),
                                 ('Benign Prostatic Hyperplasia'),
                                 ('Hemorrhoids'),
                                 ('Varicose Veins'),
                                 ('Sprain'),
                                 ('Fracture'),
                                 ('Burns'),
                                 ('Wounds'),
                                 ('Tetanus'),
                                 ('Rabies'),
                                 ('Food Poisoning'),
                                 ('Dehydration'),
                                 ('Anorexia'),
                                 ('Bulimia'),
                                 ('Tinnitus'),
                                 ('Vertigo'),
                                 ('Trigeminal Neuralgia'),
                                 ('Carpal Tunnel Syndrome'),
                                 ('Torticollis'),
                                 ('Hemiplegia'),
                                 ('Paraplegia'),
                                 ('Autism Spectrum Disorder'),
                                 ('ADHD'),
                                 ('Speech Delay'),
                                 ('Cleft Lip and Palate'),
                                 ('Clubfoot'),
                                 ('Down Syndrome'),
                                 ('Scoliosis');
select * from diagnoses;
drop table diagnoses;