INSERT INTO medicine_prices (name, price) VALUES
                                              ('Adalat LA 30mg B/30 tb', 600),
                                              ('Adalat LA 60mg B/30 tb', 700),
                                              ('Adrenaline (inj) B/10A', 800),
                                              ('Advil (200mg)', 900),
                                              ('Alanxan FR', 1000),
                                              ('Albendazol K B/1 tb', 600),
                                              ('Allertec (Syrop)', 700),
                                              ('Allertec B/100 tb', 800),
                                              ('Acetab Extra', 900),
                                              ('Alphachymotripsine', 1000),
                                              ('Alphachymotripsine B/5 A', 600),
                                              ('Alprazolam 0.5mg tb', 700),
                                              ('Amlodipine 5mg', 800),
                                              ('Amlodipine 10mg', 900),
                                              ('Amoxilline 500mg tb', 1000),
                                              ('Ampicilline 500mg B/100 tb', 600),
                                              ('Analgin B/100 tb', 700),
                                              ('Anofen 400mg B/100 tb', 800),
                                              ('Appetine (Syrop) 100ml', 900),
                                              ('Aspirine UPSA C 1T/10c', 1000),
                                              ('Aspirine 81mg tb', 600),
                                              ('Atropine (inj) B/10A', 700),
                                              ('Aluminium', 800),
                                              ('Augmentin 1g B/14 tb', 900),
                                              ('Augmentin 625mg tb', 1000),
                                              ('Alvocadyl B/100 tb', 600),
                                              ('Alvocadyl (inj) B/5A', 700),
                                              ('Acyclovir 400mg tb', 800),
                                              ('Acyclovir 200mg tb', 900),
                                              ('Azithromycin 500mg tb', 1000),
                                              ('Acetylcysteine 200mg', 600),
                                              ('Atenolol Denk 50', 700),
                                              ('Aspririne 500mg', 800),
                                              ('Albendazol 400mg', 900),
                                              ('Atorvastatin', 1000),
                                              ('Amitriptyline 25mg', 600),
                                              ('Bactrim Fort 480mg B/20 tb', 700),
                                              ('Bactrim Fort 800/160 B/10 tb', 800),
                                              ('Becilan (inj) B/5A', 900),
                                              ('Becozyme (inj) B/12A', 1000),
                                              ('Bedilix Sachet', 600),
                                              ('Bepanthene 1 T', 700),
                                              ('Bepanthene (inj) B/6A', 800),
                                              ('Berroca', 900),
                                              ('Betacef 500mg B/100 tb', 1000),
                                              ('Betacef 1500mg (inj) B/100 tb', 600),
                                              ('Betadin Dermiqeu F1/125 ml', 700),
                                              ('Betadin Thai Solution', 800),
                                              ('Betex B/250 tb', 900),
                                              ('Biofix 200mg (Cefixime) B/100 tb', 1000),
                                              ('Bioflor 250mg Sachet B/10S', 600),
                                              ('Bioflor 250mg T/10 tb', 700),
                                              ('Biothine (inj) B/6A', 800),
                                              ('Bisacodyl 5mg B/100 tb', 900),
                                              ('Bisolvon 8mg tb', 1000),
                                              ('Bisolvon (inj) B/10A', 600),
                                              ('Boska B/20 tb', 700),
                                              ('Bromhexin 8mg tb', 800),
                                              ('Bromhexin Syrop F1/60 ml', 900),
                                              ('Bromhexin 4mg (inj) B/10A', 1000),
                                              ('Budenas Spay F1/7.5ml', 600),
                                              ('Buprol 400mg', 700),
                                              ('Buscopan', 800),
                                              ('Buscopan (inj) B/10A', 900),
                                              ('Carbophos', 1000),
                                              ('Cabophose 400mg tb', 600),
                                              ('Cabotoux Adoult (Syrop)', 700),
                                              ('Ca-C 1000 Effervescen F/10 tb', 800),
                                              ('Calvit-D', 900),
                                              ('Caezar Gel', 1000),
                                              ('Calcibronat T/20 tb', 600),
                                              ('Calcium Alko (inj) B/10A', 700),
                                              ('CalCium (Buvable) Ampule', 800),
                                              ('Calcivita B/100 tb', 900),
                                              ('Candancort Cream T/15g', 1000),
                                              ('Candazol Cream T/15g', 600);
select * FROM medicine_prices;
